name: eloquent xavier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push the base Docker image
      run: |
        DOCKER_REPO=ghcr.io/autocore-ats/base-eloquent-xavier:latest
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --tag ${DOCKER_REPO} --file base.eloquent.xavier.dockerfile .
