name: eloquent pc

on:
  push:
    branches:
     - 'main'
     - 'dev'

  workflow_dispatch:

jobs:
  eloquent-pc:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_1: ghcr.io/${{ github.repository_owner }}/core-eloquent-pc:latest
      DOCKER_REPO_2: ghcr.io/${{ github.repository_owner }}/base-eloquent-pc:latest
      DOCKER_REPO_3: ghcr.io/${{ github.repository_owner }}/runtime-eloquent-pc:latest
      DOCKER_REPO_4: ghcr.io/${{ github.repository_owner }}/build-eloquent-pc:latest
      DOCKER_REPO_5: ghcr.io/${{ github.repository_owner }}/devel-eloquent-pc:latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build and push the core docker image
      run: |
        docker build . --file core.dockerfile --tag $DOCKER_REPO_1 --build-arg FROM_IMAGE=nvidia/cudagl:11.1-runtime-ubuntu18.04
        docker push $DOCKER_REPO_1
    - 
      name: Build and push the base docker image
      run: |
        docker build . --file base.eloquent.dockerfile --tag $DOCKER_REPO_2 --build-arg FROM_IMAGE=$DOCKER_REPO_1
        docker push $DOCKER_REPO_2
    - 
      name: Build and push the runtime docker image
      run: |
        docker build . --file runtime.eloquent.dockerfile --tag tmp --build-arg FROM_IMAGE=$DOCKER_REPO_2
        docker build . --file runtime.dockerfile --tag $DOCKER_REPO_3 --build-arg FROM_IMAGE=tmp
        docker push $DOCKER_REPO_3
    - 
      name: Build and push the build docker image
      run: |
        docker build . --file build.eloquent.dockerfile --tag tmp --build-arg FROM_IMAGE=$DOCKER_REPO_3
        docker build . --file build.dockerfile --tag $DOCKER_REPO_4 --build-arg FROM_IMAGE=tmp
        docker push $DOCKER_REPO_4
    - 
      name: Build and push the devel docker image
      run: |
        docker build . --file devel.dockerfile --tag $DOCKER_REPO_5 --build-arg FROM_IMAGE=$DOCKER_REPO_4
        docker push $DOCKER_REPO_5