name: foxy pc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_1: ghcr.io/autocore-ats/core-focal-pc:latest
      DOCKER_REPO_2: ghcr.io/autocore-ats/base-foxy-pc:latest
      DOCKER_REPO_3: ghcr.io/autocore-ats/runtime-foxy-pc:latest
      DOCKER_REPO_4: ghcr.io/autocore-ats/build-foxy-pc:latest
      DOCKER_REPO_5: ghcr.io/autocore-ats/devel-foxy-pc:latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build and push the core docker image
      run: |
        docker build . --file core.focal.pc.dockerfile --tag $DOCKER_REPO_1
        docker push $DOCKER_REPO_1
    - 
      name: Build and push the base docker image
      run: |
        docker build . --file base.foxy.dockerfile --tag $DOCKER_REPO_2 --build-arg FROM_IMAGE=$DOCKER_REPO_1
        docker push $DOCKER_REPO_2
    - 
      name: Build and push the runtime docker image
      run: |
        docker build . --file runtime.foxy.dockerfile --tag $DOCKER_REPO_3 --build-arg FROM_IMAGE=$DOCKER_REPO_2
        docker push $DOCKER_REPO_3
    - 
      name: Build and push the build docker image
      run: |
        docker build . --file build.foxy.dockerfile --tag $DOCKER_REPO_4 --build-arg FROM_IMAGE=$DOCKER_REPO_3
        docker push $DOCKER_REPO_4
    - 
      name: Build and push the devel docker image
      run: |
        docker build . --file devel.foxy.dockerfile --tag $DOCKER_REPO_5 --build-arg FROM_IMAGE=$DOCKER_REPO_4
        docker push $DOCKER_REPO_5