name: foxy pc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build and push the base Docker image
      run: |
        DOCKER_REPO=ghcr.io/autocore-ats/base-foxy-pc:latest
        docker build . --file base.foxy.pc.dockerfile --tag ${DOCKER_REPO}
        docker push ${DOCKER_REPO}
