name: foxy pcu

on:
  push:
    branches:
     - 'main'
     - 'dev'

  workflow_dispatch:

jobs:
  foxy-pcu:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_1: ghcr.io/${{ github.repository_owner }}/core-foxy-pcu:latest
      DOCKER_REPO_2: ghcr.io/${{ github.repository_owner }}/base-foxy-pcu:latest
      DOCKER_REPO_2_tmp: ghcr.io/${{ github.repository_owner }}/base-foxy-pcu_tmp:latest
      DOCKER_REPO_3: ghcr.io/${{ github.repository_owner }}/runtime-foxy-pcu:latest
      DOCKER_REPO_3_tmp: ghcr.io/${{ github.repository_owner }}/runtime-foxy-pcu_tmp:latest
      DOCKER_REPO_4: ghcr.io/${{ github.repository_owner }}/build-foxy-pcu:latest
      DOCKER_REPO_5: ghcr.io/${{ github.repository_owner }}/devel-foxy-pcu:latest
    steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push the core docker image
      run: docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=ubuntu:focal --tag $DOCKER_REPO_1 --file core.dockerfile .
    - 
      name: Build and push the base docker image
      run: docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_1 --tag $DOCKER_REPO_2 --file base.foxy.dockerfile .
    - 
      name: Build and push the runtime docker image
      run: |
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_2 --tag $DOCKER_REPO_2_tmp --file runtime.foxy.dockerfile .
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_2_tmp --tag $DOCKER_REPO_3 --file runtime.dockerfile .
    - 
      name: Build and push the build docker image
      run: |
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_3 --tag $DOCKER_REPO_3_tmp --file build.foxy.dockerfile .
        docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_3_tmp --tag $DOCKER_REPO_4 --file build.dockerfile .
    - 
      name: Build and push the devel docker image
      run: docker buildx build --output "type=image,push=true" --platform linux/arm64 --build-arg FROM_IMAGE=$DOCKER_REPO_4 --tag $DOCKER_REPO_5 --file devel.dockerfile .